import { LatLonName } from '../customMap/latLonByName'

export const danube: LatLonName[] = [
  'Nuremberg',
  'Regensburg',
  'Deggendorf',
  'Linz',
  'Krems',
  'Vienna',
  'Bratislava',
  'Budapest',
  'Mohacs',
  'Novi Sad',
  'Belgrade',
  'Panchevo',
  'Vidin',
  'Lom',
  'Svishtov',
  'Ruse',
  'Tutrakan',
  'Silistra',
  'Cernavoda',
  'Galati',
  'Cardon',
]
