import { sliceBorder } from '../customMap/helpers'
import { latLonByName, LatLonName } from '../customMap/latLonByName'

export const adige: LatLonName[] = [
  'Source of Adige',
  // 'Mals', The true source?
  'Sluderno',
  'Prato Allo Stelvio',
  'Merano',
  // 'Bressanone',
  'Bolzano',
  'Trento',
  'Rovereto',
  'Verona',
  'Zevio',
  "Albaredo d'Adige",
  'Legnago',
  'Badia Polesine',
  'Cavarzere',
  'Mouth of Adige',
]

export const congoRiver: LatLonName[] = [
  //
  'Source of Congo River',
  'Likasi',
  'Kongolo',
  'Kindu',
  'Kisangani',
  'Bumba',
  'Lisala',
  'Makanza',
  'Mbandaka',
  'Bolobo',
  'Kinshasa',
  'Matadi',
  // 'Matadi',
  'Mouth of Congo River',
]

export const danube: LatLonName[] = [
  // 'Hufingen',
  // 'Hufingen',
  'Donaueschingen',
  // 'Geisingen',
  'Tuttlingen',
  'Sigmaringen',
  'Mengen',
  'Riedlingen',
  'Ehingen an der Donau',
  // 'Erbach',
  'Ulm',
  'Gunzburg',
  // 'Offingen',
  'Lauingen',
  // 'Dillingen',
  'Donauworth',
  'Neuburg',
  'Ingolstadt',
  'Kelheim',
  'Regensburg',
  'Frengkofen',
  'Deggendorf',
  'Linz',
  'Krems',
  'Vienna',
  'Bratislava',
  'Gonyu',
  'Veroce',
  'Vac',
  'Budapest',
  'Mohacs',
  'Vucovar',
  'Novi Sad',
  'Belgrade',
  'Panchevo',
  'Grocka',
  'Smederevo',
  'Kovin',
  'Veliko Gradiste',
  'Golubac',
  // 'Dubova',
  'Orsova',
  'Drobeta-Turnu Severin',
  'Negotin',
  'Vidin',
  'Lom',
  'Corabia',
  'Svishtov',
  'Ruse',
  'Tutrakan',
  'Silistra',
  'Rasova',
  'Cernavoda',
  'Harsova',
  'Braila',
  'Galati',
  'Reni',
  'Cardon',
]

export const dnieper: LatLonName[] = [
  //
  'Source of Dnieper',
  'Smolensk',
  'Orsha',
  'Mahilyow',
  'Rahachow',
  'Kyiv',
  'Cherkasy',
  'Kremenchuk',
  'Dnipro',
  'Zaporizhzhia',
  'Nikopol',
  'Nova Kakhovka',
  'Kherson',
  'Mouth of Dnieper',
]

export const dniester: LatLonName[] = [
  'Chaicovychi',
  'Sambir',
  'Staryi Sambir',
  'Verkhniy Luzhok',
  'Dnistryk',
  'Source of Dniester', // This starts to go in rounds???
  'Berezyna',
  'Kamyane',
  'Zhuravno',
  'Burshtyn',
  'Khotyn',
  'Novodnistrovsk',
  'Mohyliv-Podilskyi',
  'Yampil',
  'Ribnita',
  'Dubasari',
  'Tiraspol',
  'Mouth of Dniester',
]

export const don: LatLonName[] = [
  'Source of Don',
  'Voronezh',
  'Liski',
  'Volgodonsk',
  'Rostov',
  'Mouth of Don',
]

export const elbe: LatLonName[] = [
  'Pramen Labe',
  'Spindleruv Mlyn',
  // 'Labska',
  'Vrchlabi',
  // 'Kunice nad Labem',
  // 'Hostinne',
  // 'Nemojov',
  'Jaromer',
  'Hradec Kralove',
  // 'Opatovice nad Labem',
  // 'Sesemice',
  'Pardubice',
  'Prelouc',
  'Kolin',
  'Nymburk',
  'Celakovice',
  'Neratovice',
  'Melnik',
  'Kresice',
  'Lovosice',
  'Usti nad Labem',
  'Povrly',
  'Techlovice',
  'Malsovice',
  'Decin',
  'Muhlgrundbach',
  'Dresden',
  // 'Nunchritz',
  'Riesa',
  // 'Muhlberg',
  'Greudnitz',
  'Elster',
  'Wittenberg',
  // 'Anhalt',
  'Aken',
  'Magdeburg',
  'Ferchland',
  'Tangermunde',
  'Werben',
  'Wittenberge',
  'Hamburg',
  'Stadersand',
  'Brunsbuttel',
  'Cuxhaven',
]

export const ganges: LatLonName[] = [
  //
  'Source of Ganges',
  'Kanpur',
  'Prayagraj',
  'Mirzapur',
  'Varanasi',
  'Ballia',
  'Patna',
  'Bhagalpur',
  'Sahibganj',
  'Farakka',
  'Rajshahi',
  'Daulatdia',
  'Chandpur',
  // 'Kolkata',
  'Mouth of Ganges',
]

export const brahmaputra: LatLonName[] = [
  //
  'Source of Brahmaputra',
  'Zuobudun',
  'Zhelong',
  'Tangguocun',
  'Lhatse',
  'Xaitongmoin',
  'Nang County',
  'Mainling',
  'Sedongpu',
  'Duoka Village',
  'Lengduo',
  'Gelling',
  'Migging',
  'Boleng',
  'Pasighat',
  'Jorhat',
  'Tezpur',
  'Guwahati',
  'Mouth of Brahmaputra',
  ...sliceBorder(ganges, 'Daulatdia'),
]

export const garonne: LatLonName[] = [
  'Source of Garonne',
  'Saint-Gaudens',
  // 'Carbonne',
  'Toulouse',
  'Moissac',
  'Agen',
  // 'Aiguillon',
  'Marmande',
  // 'Langon',
  'Bordeaux',
  'Royan',
]

export const indusRiver: LatLonName[] = [
  //
  'Source of Indus River',
  'Lahore',
  'Sehwan',
  'Hyderabad (Pakistan)',
  'Mouth of Indus River',
]

export const jordanRiver: LatLonName[] = [
  //
  'Source of Jordan River',
  'Mouth of Jordan River',
]

export const kizilirmak: LatLonName[] = [
  //
  'Source of Kizilirmak',
  'Mouth of Kizilirmak',
]

export const loire: LatLonName[] = [
  'Sources de la Loire',
  // 'Sainte-Eulalie',
  'Rieuford',
  'Pont de la Loire',
  'Issarles',
  'Arlempdes',
  // 'Goudet',
  // 'Coubon',
  'Brives-Charensac',
  'Chadrac',
  'Vorey',
  'Pont de Lignon',
  'Roanne',
  'Digoin',
  // 'Decize',
  'Nevers',
  // 'Briare',
  'Gien',
  'Orleans',
  'Tours',
  'Angers',
  'Nantes',
  'Saint-Nazaire',
]

export const nigerRiver: LatLonName[] = [
  //
  'Source of Niger River',
  'Faranah',
  'Kouroussa',
  'Bamako',
  'Mopti',
  'Timbuktu',
  'Gourma Rharous',
  'Bourem',
  'Niamey',
  'Tondi',
  'Jebba',
  'Lokoja',
  'Onitsha',
  'Mouth of Niger River', // splits into two sub streams right before ocean
  'Okumbiri', // beach between the substreams
]

export const nile: LatLonName[] = [
  //
  'Source of Nile',
  'Juba',
  'Khartoum',
  'Aswan',
  'Luxor',
  'Cairo',
]

export const rhine: LatLonName[] = [
  'Stein am Rhein',
  'Neuhausen am Rheinfall',
  'Eglisau',
  'Waldshut',
  'Bad Sackingen',
  'Basel',
  'Neuenburg am Rhein',
  'Breisach am Rhein',
  // Strasbourg
  'Kehl',
  'Worth am Rhein',
  'Speyer',
  'Mannheim',
  // 'Wiesbaden',
  'Mainz',
  'Bingen am Rhein',
  // 'Rudesheim',
  'Koblenz',
  'Neuwied',
  'Andernach',
  'Bad Honnef am Rhein',
  'Bonn',
  'Cologne',
  'Dusseldorf',
  'Duisburg',
  'Wesel',
  'Nijmegen',
  'Tiel',
  'Zaltbommel',
  'Werkendam',
  'Willemstad',
  'Rockanje',
]

export const meuse: LatLonName[] = [
  'Source of Meuse',
  'Verdun',
  'Namur',
  'Liege',
  'Maastricht',
  'Roermond',
  'Venlo',
  ...sliceBorder(rhine, 'Nijmegen'),
]

export const oder: LatLonName[] = [
  //
  'Source of Oder',
  'Ostrava',
  'Opole',
  'Wroclaw',
  'Zielona Gora',
  'Frankfurt (Oder)',
  'Szczecin',
  'Mouth of Oder',
]

export const po: LatLonName[] = [
  'Source of Po',
  'Saluzzo',
  'Turin',
  'Chivasso',
  'Casale Monferrato',
  'Valenza',
  'Pavia',
  'Placentia',
  'Cremona',
  'Guastalla',
  'Suzzara',
  'Bergantino',
  'Santa Maria Maddalena',
  'Mouth of Po',
]

export const rhone: LatLonName[] = [
  'Rhone Glacier',
  'Sion',
  'Martigny',
  'Montreux',
  'Lausanne',
  'Geneva',
  'Valserhone',
  'Seyssel',
  'Belley',
  'Tremurs',
  'Lagnieu',
  'Lyon',
  'Vienne',
  'Valence',
  'Montelimar',
  'Avignon',
  'Arles',
]

export const seine: LatLonName[] = [
  'Sources de la Seine',
  // 'Chatillon',
  'Troyes',
  'Paris',
  'Rouen',
  'Le Havre',
]

export const tiber: LatLonName[] = [
  'Source of Tiber',
  'Sansepolcro',
  'Perugia',
  'Todi',
  'Baschi Scalo',
  'Passo Corese',
  'Rome',
  'Mouth of Tiber',
]

export const tigris: LatLonName[] = [
  //
  'Source of Tigris',
  'Diyarbakir',
  'Batman',
  'Cizre',
  'Mosul',
  'Tikrit',
  "Samarra'",
  'Baghdad',
  'Al Kut',
  'Al `Amarah',
  // 'Mouth of Tigris',
  'Al Qurnah',
  'Al Basrah',
  'Abadan',
]

export const euphrates: LatLonName[] = [
  //
  'Source of Euphrates',
  'Keban',
  'Egribuk',
  'Gecitkoy',
  'Kayalar',
  'Jarabulus',
  'Ar Raqqah',
  // 'Madan',
  "Al Qa'im",
  'Hadithah',
  'Ar Ramadi',
  'Al Fallujah',
  'An Najaf',
  'Muthanna',
  'As Samawah',
  'An Nasiriyah',
  // 'Mouth of Euphrates',
  ...sliceBorder(tigris, 'Al Qurnah'),
]

export const vistula: LatLonName[] = [
  //
  'Source of Vistula',
  'Krakow',
  'Sandomierz',
  'Warsaw',
  'Plock',
  'Wloclawek',
  'Torun',
  // 'Bygdoszcz',
  // 'Grudziadz',
  // 'Gdansk',
  'Mouth of Vistula',
]

export const vltava: LatLonName[] = [
  'Pramen Vltavy',
  'Kvilda',
  'Borova Lada',
  'Horni Vltavice',
  'Lenora',
  'Chlumsky Potok',
  'Vyssi Brod',
  'Parkoviste',
  'Cesky Krumlov',
  'Ceske Budejovice',
  'Prague',
  'Kralupy nad Vltavou',
  'Melnik',
  ...sliceBorder(elbe, 'Melnik'),
]

export const volga: LatLonName[] = [
  'Source of Volga',
  'Rzhev',
  'Tver',
  'Dubna',
  'Rybinsk',
  'Yaroslavl',
  'Nizhniy Novgorod',
  'Kazan',
  'Ulyanovsk',
  'Samara',
  'Saratov',
  'Volgograd',
  'Astrakhan',
  'Mouth of Volga',
]

export const yangtse: LatLonName[] = [
  //
  'Source of Yangtse',
  'Lijiang',
  'Chongqing',
  'Fengdu County',
  'Yunyang County',
  'Yichang',
  // 'Jingzhou',
  'Yueyang',
  'Wuhan',
  'Jiujiang',
  'Anqing',
  'Chizhou',
  // 'Tongling',
  'Wuhu',
  // 'Maanshan',
  'Nanjing',
  'Zhenjiang',
  'Nantong',
  'Shanghai',
  'Mouth of Yangtse',
]

export const yellowRiver: LatLonName[] = [
  //
  'Source of Yellow River',
  'Changna',
  'Jiarihai',
  'Longyang',
  'Lanzhou',
  'Yinchuan',
  'Byannur',
  'Baotou',
  'Yushuwan',
  'Sanmenxia',
  'Zhengzhou',
  'Jiahetan',
  'Jinan',
  'Mouth of Yellow River',
]

export const zambezi: LatLonName[] = [
  //
  'Source of Zambezi',
  'Cazombo',
  'Mongu',
  'Livingstone',
  'Kariba',
  'Tete',
  'Mouth of Zambezi',
]

export const rivers = [
  adige,
  brahmaputra,
  congoRiver,
  danube,
  dnieper,
  dniester,
  don,
  elbe,
  euphrates,
  ganges,
  garonne,
  indusRiver,
  jordanRiver,
  kizilirmak,
  loire,
  meuse,
  nigerRiver,
  nile,
  oder,
  po,
  rhine,
  rhone,
  seine,
  tiber,
  tigris,
  vistula,
  vltava,
  volga,
  yangtse,
  yellowRiver,
  zambezi,
].map((river) => river.map((name) => latLonByName[name]))
