import { latLonByName } from "./latLonByName";
import { latLonTupleToXYTuple } from "./helpers";

const europe: (keyof typeof latLonByName)[] = [
  "Tanais",
  "Mariupol",
  "Henichesk",
  "Kerch",
  "Sevastopol",
  "Yevpatoriya",
  "Olenivka",
  "Krasnoperekopsk",
  "Kherson",
  "Odesa",
  "Varna",
  "Burgas",
  "Rumelifeneri",
  "Istanbul",
  "Tekirdag",
  "Sarkoy",
  "Seddulbahir",
  "Anzak",
  "Kocacesme",
  "Sultanice",
  "Alexandroupoli",
  "Kavala",
  "Stavros",
  "Katounakia",
  "Kalamitsi",
  "Loutra",
  "Thessaloniki",
  "Limenas",
  "Volos",
  "Phthia",
  "Nea Makri",
  "Sounion",
  "Piraeus",
  "Isthmias",
  "Korfos",
  "Mpiseika",
  "Kranidi",
  "Nafplion",
  "Myloi",
  "Myloi",
  "Ariana",
  "Xifias",
  "Eklisia",
  "Korakas",
  "Archangelos",
  "Kokkinia",
  "Trinisa",
  "Gytheio",
  "Kotronas",
  "Kokkinogia",
  "Gerolimenas",
  "Oitylo",
  "Kalamata",
  "Tzanes",
  "Koroni",
  "Methoni",
  "Kyllini",
  "Patras",
  "Corinth",
  "Psatha",
  "Galaxidi",
  "Missolonghi",
  "Vlore",
  "Durres",
  "Lezhe",
  "Ulcinj",
  "Bar",
  "Budva",
  "Dubrovnik",
  "Split",
  "Zadar",
  "Senj",
  "Rijeka",
  "Pula",
  "Umag",
  "Trieste",
  "Venice",
  "Ravenna",
  "Ancona",
  "Pescara",
  "Bari",
  "Monopoli",
  "Brindisi",
  "Otranto",
  "Santa Maria di Leuca",
  "Gallipoli",
  "Taranto",
  "Trebisacce",
  "Ciro Marina",
  "Crotone",
  "Galati",
  "Roghudi",
  "Reggio di Calabria",
  "Cafarone",
  "Sapri",
  "Naples",
  "Ostia",
  "Grosseto",
  "Pisa",
  "Genoa",
  "Savona",
  "Imperia",
  "Nice",
  "Toulon",
  "Marseille",
  "Montpellier",
  "Narbonne",
  "Girona",
  "Barcelona",
  "Tarragona",
  "Valencia",
  "Denia",
  "Alicante",
  "Cartagena",
  "Almeria",
  "Malaga",
  "Gibraltar",
  "Cadiz",
  "Huelva",
  "Faro",
  "Sagres",
  "Zambujeira",
  "Sines",
  "Setubal",
  "Cascais",
  "Peniche",
  "Porto",
  "Vigo",
  "Camarinas",
  "A Coruna",
  "Carino",
  "Foz",
  "Gijon",
  "Comillas",
  "Santander",
  "Sorrozuela",
  "Bilbao",
  "Donostia",
  "Bayonne",
  "La Rochelle",
  "Vannes",
  "Quimper",
  "Brest",
  "Lannion",
  "Saint-Brieuc",
  "Saint-Malo",
  "Granville",
  "Flamanville",
  "Cherbourg",
  "Barfleur",
  "Crasville",
  "Utah Beach",
  "Ouistreham",
  "Le Havre",
  "Etretat",
  "Treport",
  "Calais",
  "Dunkirk",
  "Bruges",
  "Rotterdam",
  "Amsterdam",
  "Groningen",
  "Bremerhaven",
  "Husum",
  "Esbjerg",
  "Agger",
  "Hanstholm",
  "Hirtshals",
  "Frederikshavn",
  "Aarhus",
  "Odense",
  "Helsingor",
  "Copenhagen",
  "Lubeck",
  "Stralsund",
  "Gdansk",
  "Kaliningrad",
  "Klaipeda",
  "Ventspils",
  "Riga",
  "Parnu",
  "Haapsalu",
  "Tallinn",
  "Saint Petersburg",
  "Vyborg",
  "Kotka",
  "Helsinki",
  "Hanko",
  "Turku",
  "Uusikaupunki",
  "Rauma",
  "Pori",
  "Narpes",
  "Vaasa",
  "Kokkola",
  "Raahe",
  "Oulu",
  "Olhava",
  "Kemi",
  "Tornio",
  "Tore",
  "Lulea",
  "Pitea",
  "Skelleftea",
  "Bjuroklubb",
  "Umea",
  "Bjasta",
  "Sundsvall",
  "Hudiksvall",
  "Gavle",
  "Osthammar",
  "Norrtalje",
  "Stockholm",
  "Nykoping",
  "Kalmar",
  "Malmo",
  "Halmstad",
  "Gothenburg",
  "Fredrikstad",
  "Oslo",
  "Sandefjord",
  "Kristiansand",
  "Hauge",
  "Bryne",
  "Stavanger",
  "Bergen",
  "Alesund",
  "Trondheim",
  "Bodo",
  "Harstad",
  "Tromso",
  "Hammerfest",
  "Mehamn",
  "Kirkenes",
  "Teriberka",
  "Lumbovka",
  "Mayak",
  "Sosnovka",
  "Strelna",
  "Kandalaksha",
  "Kem",
  "Onega",
  "Arkhangelsk",
];

const asia: (keyof typeof latLonByName)[] = [
  "Arkhangelsk",
  "Chizha",
  "Tiksi",
  "Naukan",
  "Ozernovskiy",
  "Manily",
  "Yamsk",
  "Magadan",
  "Okhotks",
  "Chumikan",
  "Makarovka",
  "Koppi",
  "Olga",
  "Nakhodka",
  "Vladivostok",
  "Wonsan",
  "Kosong",
  "Yewon",
  "Pohang",
  "Busan",
  "Mokpo",
  "Incheon",
  "Pyongyang",
  "Dandong",
  "Dalian",
  "Yingkou",
  "Huludao",
  "Qinhuangdao",
  "Qingdao",
  "Shanghai",
  "Taizhou",
  "Quanzhou",
  "Hong Kong",
  "Zhanjiang",
  "Beihai",
  "Haiphong",
  "Vinh",
  "Quang Ngai",
  "Nha Trang",
  "Can Tho",
  "Bangkok",
  "Surat Thani",
  "Kuala Terengganu",
  "Kuantan",
  "Kampung Gambut",
  "Singapore",
  "Muar",
  "Port Dickson",
  "George Town",
  "Alot Setar",
  "Talat Yai",
  "Myeik",
  "Mawlamyine",
  "Chattogram",
  "Digha",
  "Vishakhapatnam",
  "Ongole",
  "Chennai",
  "Puducherry",
  "Nagapattinam",
  "Thoothukudi",
  "Kanniyakumari",
  "Thiruvananthapuram",
  "Kochi",
  "Mumbai",
  "Surat",
  "Diu",
  "Karachi",
  "Gwadar",
  "Chabahar",
  "Kooh",
  "Kolahi",
  "Bandar `Abbas",
  "Mollu",
  "Bushehr",
  "Abadan",
  "Kuwait City",
  "Dammam",
  "Al Mirfa",
  "Abu Dhabi",
  "Dubai",
  "Sharjah",
  "Ras Al-Khaimah",
  "Khasab",
  "Sall Ala",
  "Fujairah",
  "Sohar",
  "Muscat",
  "Al Hadd",
  "Ras Madrakah",
  "Salalah",
  "Al Mukalla",
  "Aden",
  "Jeddah",
  "Sharma",
  "Ras Gasabah",
  "Aqaba",
  "Sharm El-Sheikh",
  "Suez",
  "Port Said",
  "Rafah",
  "Gaza",
  "Tel Aviv-Yafo",
  "Beirut",
  "Iskenderun",
  "Mersin",
  "Anamur",
  "Alanya",
  "Antalya",
  "Fethiye",
  "Bodrum",
  // "Izmir",
  "Cesme",
  "Babakale",
  "Canakkale",
  "Adatepe",
  "Bandirma",
  // "Bursa",
  "Yalova",
  "Golcuk",
  "Izmit",
  "Gebze",
  "Istanbul",
  "Riva",
  "Sile",
  "Babali",
  "Karasu",
  "Akcakoca",
  "Alapli",
  "Eregli",
  "Zonguldak",
  "Ilyasbey",
  "Ayancik",
  "Sinop",
  "Gerze",
  "Yakakent",
  "Samsun",
  "Trabzon",
  "Rize",
  "Batumi",
  "Sochi",
  "Novorossiysk",
  "Yeysk",
  "Azov",
  "Tanais",
];

const africa: (keyof typeof latLonByName)[] = [
  "Suez",
  "Djibouti",
  "Tohen",
  "Mogadishu",
  "Mombasa",
  "Nampula",
  "Durban",
  "Gqeberha",
  "Cape Town",
  "Luanda",
  "Lagos",
  "Monrovia",
  "Dakar",
  "Agadir",
  "Essaouira",
  "El Jadida",
  "Casablanca",
  "Rabat",
  "Tangier",
  "Ceuta",
  "Tetouan",
  "Nador",
  "Oran",
  "Algiers",
  "Tunis",
  "Sousse",
  "Monastir",
  "Chebba",
  "Sfax",
  "Skhira",
  "Gabes",
  "Zuwara",
  "Tripoli",
  "Misrata",
  "Buerat",
  "Sirte",
  "Bin Jawad",
  "Ras Lanuf",
  "Al Uqaylah",
  "Sultan",
  "Benghazi",
  "Al Bayda",
  "Sidi Barrani",
  "Marsa Matruh",
  "Marina El Alamein",
  "Alexandria",
  "Damietta",
  "Port Said",
];

export const europeBorder = europe.map((name) => {
  const latLon = latLonByName[name];
  const lat = latLon[0] || 0;
  const lon = latLon[1] || 0;
  return latLonTupleToXYTuple([lat, lon]);
});

export const africaBorder = africa.map((name) => {
  const latLon = latLonByName[name];
  const lat = latLon[0] || 0;
  const lon = latLon[1] || 0;
  return latLonTupleToXYTuple([lat, lon]);
});

export const asiaBorder = asia.map((name) => {
  const latLon = latLonByName[name];
  const lat = latLon[0] || 0;
  const lon = latLon[1] || 0;
  return latLonTupleToXYTuple([lat, lon]);
});
